# https://alacritty.org/config-alacritty.html

[general]
live_config_reload = true #  changes take place on save
import = [
  "~/.config/alacritty/catppuccin-mocha.toml",
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "Hack Nerd Font", style = "Regular"}
size = 16

[window]
startup_mode = "Maximized"
option_as_alt = "Both"
decorations = "Buttonless"
padding = { x = 4, y = 4 }
dynamic_padding = true
# opacity = 0.55
# blur = true

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  { key = "Q", mods = "Command", action = "None" }, # disable command q
  { key = "Space", mods = "Command", chars = "\u001b[99~"}, # escape sequence to launch sesh
  { key = "t", mods = "Command", chars = "\u0002c"}, # new tmux window
  { key = "w", mods = "Command", chars = "\u0002x"}, # close tmux pane/window
  { key = "1", mods = "Command", chars = "\u00021"}, # go to tmux window 1
  { key = "2", mods = "Command", chars = "\u00022"}, # go to tmux window 2
  { key = "3", mods = "Command", chars = "\u00023"}, # go to tmux window 3
  { key = "4", mods = "Command", chars = "\u00024"}, # go to tmux window 4
  { key = "5", mods = "Command", chars = "\u00025"}, # go to tmux window 5
  { key = "6", mods = "Command", chars = "\u00026"}, # go to tmux window 6
  { key = "7", mods = "Command", chars = "\u00027"}, # go to tmux window 7
  { key = "8", mods = "Command", chars = "\u00028"}, # go to tmux window 8
  { key = "9", mods = "Command", chars = "\u00029"}, # go to tmux window 9
  { key = "Left", mods = "Command", chars = "\u0002\u001b[D"}, # navigate to pane, left
  { key = "Down", mods = "Command", chars = "\u0002\u001b[B"}, # navigate to pane, down
  { key = "Up", mods = "Command", chars = "\u0002\u001b[A"}, # navigate to pane, up
  { key = "Right", mods = "Command", chars = "\u0002\u001b[C"}, # navigate to pane, right
]
